config/routes.rb
ClassiqueKitchens::Application.routes.draw do
  root to: 'page#home'

  resources :kitchens
  resources :features
  resources :sessions
  resources :users

  get 'contact' => 'contact#new'
  put 'contact' => 'contact#create'

  get 'stormer_kitchens'    => 'stormer_kitchens#index'
  get 'hand_made_furniture' => 'hand_made_furniture#index'
end

app/models/kitchen.rb
class Kitchen < ActiveRecord::Base
  attr_accessible :name, :image, :type, :featured
  validates :name, presence: true
  validates :name, uniqueness: true

  has_attached_file :image, {
    styles: { featured: '940x529#', main: '540x405#' },
    url: '/system/kitchens/:attachment/:id/:basename_:style.:extension'
  }.merge(PAPERCLIP_STORAGE_OPTIONS)

  validates_attachment_presence :image

  def self.featured
    self.where(featured: true)
  end

  def self.inherited(child)
    child.instance_eval do
      def model_name
        Kitchen.model_name
      end
    end

    super
  end

  def self.select_options
    descendants.map{ |c| c.to_s }.sort
  end

  # TODO: extract this into presenter/exhibit
  def self.type
    "All Kitchens"
  end

  def self.active_nav_item
    'Kitchens'
  end

  def self.description
    RDiscount.new(<<DESC).to_html
Our kitchens are carefully selected from high quality branded European
suppliers, ensuring you the very latest in cutting edge design and innovation.
Our portfolio of over 50 ranges include high gloss lacquers, carbon acrylic
through to our bespoke handmade furniture.

When combined with quality appliances and a choice from our wide variety of
work surfaces, the results are simply stunning.
DESC
  end
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  before_filter :authorise

  def new
    @kitchen = Kitchen.new
  end

  def show
    @kitchen = Kitchen.find(params[:id])
  end

  def edit
    @kitchen = Kitchen.find(params[:id])
  end

  def create
    @kitchen = Kitchen.new(params[:kitchen])

    if @kitchen.save
      redirect_to @kitchen, notice: 'Kitchen was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @kitchen = Kitchen.find(params[:id])

    if @kitchen.update_attributes(params[:kitchen])
      redirect_to @kitchen, notice: 'Kitchen was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @kitchen = Kitchen.find(params[:id])
    @kitchen.destroy

    redirect_to kitchens_url
  end
end

app/views/kitchens/_form.html.haml
= simple_form_for(@kitchen, html: { :class => 'form-horizontal' }) do |f|
  %fieldset
    %legend
      = controller.action_name.capitalize
      Kitchen

    = f.input :name, value: @kitchen.name
    = f.input :featured, value: @kitchen.featured?
    = f.input :type, collection: Kitchen.select_options
    = f.input :image, as: :file

    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', @kitchen, :class => 'btn'

app/views/kitchens/_slideshow.html.haml
#slideshow.kitchens
  - @kitchens.each do |kitchen|
    %div{:class => "kitchen #{kitchen.name.parameterize}"}
      - if current_user
        .actions
          = link_to 'New Kitchen', new_kitchen_path, :class => 'btn btn-mini'
          = link_to 'Edit', edit_kitchen_path(kitchen), :class => 'btn btn-mini' 
          = link_to 'Delete', kitchen, :class => 'btn btn-mini btn-danger'
      %img.image{src: kitchen.image.url(:main), alt: kitchen.name}

app/views/kitchens/show.html.haml
%h1 Kitchen

%p
  %b Name
  %br
  = @kitchen.name

%p
  %b Type
  %br
  = @kitchen.type

%p
  %b Image
  %br
  = image_tag @kitchen.image.url

.form-actions
  = link_to 'Back', kitchens_path, :class => 'btn'
  = link_to 'Edit', edit_kitchen_path(@kitchen), :class => 'btn'
  = link_to 'Delete', kitchen_path(@kitchen), method: 'delete', confirm: 'Are you sure?', :class => 'btn btn-danger'