config/routes.rb
ClassiqueKitchens::Application.routes.draw do
  root to: 'page#home'

  resources :kitchens
  resources :features
  resources :sessions
  resources :users

  get 'contact' => 'contact#new'
  put 'contact' => 'contact#create'

  get 'stormer_kitchens'    => 'stormer_kitchens#index'
  get 'hand_made_furniture' => 'hand_made_furniture#index'
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  attr_accessible :content, :image

  has_attached_file :image, {
    styles: { main: '200x230#' }
  }.merge(PAPERCLIP_STORAGE_OPTIONS)

  validates_attachment_presence :image

  # TODO: Put this in its place
  def content_html
    RDiscount.new(self.content).to_html.strip.encode('US-ASCII', invalid: :replace)
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_filter :authorise

  def new
    @feature = Feature.new
  end

  def show
    @feature = Feature.find(params[:id])
  end

  def edit
    @feature = Feature.find(params[:id])
  end

  def create
    @feature = Feature.new(params[:feature])

    if @feature.save
      redirect_to @feature, notice: 'Feature was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @feature = Feature.find(params[:id])

    if @feature.update_attributes(params[:feature])
      redirect_to @feature, notice: 'Feature was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy

    redirect_to features_url
  end
end

app/views/features/_feature.html.haml
.feature
  = image_tag feature.image.url(:main)
  = raw feature.content_html
  - if current_user
    .actions
      = link_to 'Edit', edit_feature_path(feature), :class => 'btn btn-mini' 
      = link_to 'Delete', feature, :class => 'btn btn-mini btn-danger'

app/views/features/_form.html.haml
= simple_form_for(@feature, html: { :class => 'form-horizontal' }) do |f|
  %fieldset
    %legend
      = controller.action_name.capitalize
      Feature

    = f.input :content, value: @feature.content
    = f.input :image, as: :file

    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', @feature, :class => 'btn'

app/views/features/edit.html.haml
= render 'form'

app/views/features/show.html.haml
= image_tag @feature.image.url
= raw @feature.content_html

.form-actions
  = link_to 'Back', stormer_kitchens_path, :class => 'btn'
  = link_to 'Edit', edit_feature_path(@feature), :class => 'btn'
  = link_to 'Delete', feature_path(@feature), method: 'delete', confirm: 'Are you sure?', :class => 'btn btn-danger'